### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by alfreb** [includeos/includeos-tools#11]
I suddenly experienced this, after a few successful calls: 
```
ostack --instant
name: build  image: ./IncludeOS_example.img
Traceback (most recent call last):
  File "/home/ubuntu/includeos-tools/openstack_control/openstack_control.py", line 340, in <module>
    main()
  File "/home/ubuntu/includeos-tools/openstack_control/openstack_control.py", line 332, in main
    service_name = instant()
  File "/home/ubuntu/includeos-tools/openstack_control/openstack_control.py", line 249, in instant
    vm_delete(service_name)
  File "/home/ubuntu/includeos-tools/openstack_control/openstack_control.py", line 105, in vm_delete
    vm_status(name)['server'].delete()
  File "/usr/lib/python2.7/dist-packages/novaclient/v2/servers.py", line 51, in delete
    return self.manager.delete(self)
  File "/usr/lib/python2.7/dist-packages/novaclient/v2/servers.py", line 1294, in delete
    return self._delete("/servers/%s" % base.getid(server))
  File "/usr/lib/python2.7/dist-packages/novaclient/base.py", line 354, in _delete
    resp, body = self.api.client.delete(url)
  File "/usr/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 188, in delete
    return self.request(url, 'DELETE', **kwargs)
  File "/usr/lib/python2.7/dist-packages/novaclient/client.py", line 94, in request
    raise exceptions.from_response(resp, body, url, method)
novaclient.exceptions.NotFound: Instance e359082b-ecb2-45e0-bc5a-1ef90808d6bd could not be found. (HTTP 404) (Request-ID: req-843cbadb-242c-4670-964a-7da7f7794d17)
```

Looks like it's trying to delete an instance that doesn't exist?

**Comment by mnordsletten** [comment]
It does look like it is trying to delete one that doesn't exist. That shouldn't cause an issue, as I'm catching that, but I'll fix it on thursday.
